language: node_js
node_js:
 - "8"
 - "10"
 - "node"
install: npm install --ignore-scripts
script:
  - npm run build
  - npm run lint
  - npm test
  - npm run spec-tordf
  - npm run spec-stream-tordf
after_success:
  - npm run coveralls
cache:
  - npm
  - directories:
    - .rdf-test-suite-cache
